<a href="https://colab.research.google.com/github/LeoFernanndes/notebooks/blob/master/CFD_TC2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np


indices = np.arange((N+1)+1)

T0 = 0
TL = 1

a = np.full(N+1, 2)
b = np.full(N+1, 0)


P = np.zeros((N + 1) + 1)
Q = np.zeros((N + 1) + 1)
T = np.zeros((N + 1) + 1)
Tr = np.zeros((N + 1) + 1)

for i in indices:
  if i == 0:
    
    aw = 0
    ap = 1
    ae = 0
    bp = T0

    P[i] = ae / ap
    Q[i] = bp / ap

  if i > 0:
    aw = 1
    ap = 2
    ae = 1
    bp = 0

    P[i] = ae /(ap - aw * P[i-1])
    Q[i] = (bp + aw * Q[i-1]) / (ap - aw * P[i-1])

  if i == N+1:
    aw = 0
    ap = 1
    ae = 0
    bp = TL

    P[i] = ae /(ap - aw * P[i-1])
    Q[i] = (bp + aw * Q[i-1]) / (ap - aw * P[i-1])

for i in reversed(indices):
  if i == N+1:
    T[i] = Q[N+1]
  if i < N+1:
    T[i] = P[i] * T[i+1]  + Q[i]   

for i in indices:
  Tr[i] = i / (N + 1)

tabela = pd.DataFrame({'Indice': indices,
                       'P': P,
                       'Q': Q,
                       'T_numerica': T,
                       'T_real': Tr})

In [70]:
tabela

    Indice         P    Q  T_numerica  T_real
0        0  0.000000  0.0         0.0     0.0
1        1  0.500000  0.0         0.1     0.1
2        2  0.666667  0.0         0.2     0.2
3        3  0.750000  0.0         0.3     0.3
4        4  0.800000  0.0         0.4     0.4
5        5  0.833333  0.0         0.5     0.5
6        6  0.857143  0.0         0.6     0.6
7        7  0.875000  0.0         0.7     0.7
8        8  0.888889  0.0         0.8     0.8
9        9  0.900000  0.0         0.9     0.9
10      10  0.000000  1.0         1.0     1.0